# Generated by Django 5.2.4 on 2025-08-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=60)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("brand", models.CharField(default="Generic", max_length=60)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("material", models.CharField(blank=True, max_length=40, null=True)),
                ("available_sizes", models.JSONField(default=list)),
                ("in_stock", models.BooleanField(default=True)),
                ("rating", models.FloatField(default=0.0)),
                ("num_reviews", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
